import 'package:flutter/material.dart';

enum PaletteCategory {
  trainTransit('Train/Transit'),
  warm('Warm'),
  cool('Cool'),
  darkMoody('Dark/Moody'),
  earth('Earth'),
  vibrant('Vibrant'),
  pastel('Pastel'),
  special('Special'),
  monochrome('Monochrome'),
  jewelTones('Jewel Tones'),
;
  final String label;
  const PaletteCategory(this.label);
}

class AppPalette {
  final String id;
  final String name;
  final List<Color> colors;
  final PaletteCategory category;

  const AppPalette({
    required this.id,
    required this.name,
    required this.colors,
    required this.category,
  });
}

const List<AppPalette> allPalettes = [
  AppPalette(id: 'electric', name: 'Electric', colors: [Color(0xFF1B4FE4), Color(0xFFFF4757), Color(0xFFFFE100), Color(0xFF00E59B), Color(0xFF0D0D0D)], category: PaletteCategory.vibrant),
  AppPalette(id: 'wabi_sabi', name: 'Wabi-Sabi', colors: [Color(0xFFF4EEE0), Color(0xFF9E7B5A), Color(0xFF6B7C49), Color(0xFF2F2B24), Color(0xFFEAE0D5)], category: PaletteCategory.earth),
  AppPalette(id: 'coastal_edit', name: 'Coastal Edit', colors: [Color(0xFFE8D5B7), Color(0xFF2A7B9B), Color(0xFFA8D8CF), Color(0xFF8B6F47), Color(0xFFF2F7F5)], category: PaletteCategory.cool),
  AppPalette(id: 'luxury_noir', name: 'Luxury Noir', colors: [Color(0xFF1A1A1A), Color(0xFFD4AF37), Color(0xFFF8F4E3), Color(0xFF9C4B1B), Color(0xFFE5E5E5)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'sage_clay', name: 'Sage & Clay', colors: [Color(0xFFB2C5A8), Color(0xFFC4785A), Color(0xFFF5F0E8), Color(0xFF7A8B8B), Color(0xFF5C4A3A)], category: PaletteCategory.earth),
  AppPalette(id: 'velvet_noir', name: 'Velvet Noir', colors: [Color(0xFF1C1C1E), Color(0xFF6E1423), Color(0xFFE8D9B5), Color(0xFF4A4A4F), Color(0xFFF2F0EB)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'citrus_grove', name: 'Citrus Grove', colors: [Color(0xFFFF8A1E), Color(0xFFB6D94C), Color(0xFFFFF6E0), Color(0xFF5A3E2B), Color(0xFF262220)], category: PaletteCategory.warm),
  AppPalette(id: 'monsoon', name: 'Monsoon', colors: [Color(0xFF2C3E76), Color(0xFF6E7B8B), Color(0xFF4F6B4D), Color(0xFFEDF1F2), Color(0xFF1A1F26)], category: PaletteCategory.cool),
  AppPalette(id: 'harvest_table', name: 'Harvest Table', colors: [Color(0xFFD9762B), Color(0xFFE8C77E), Color(0xFF7C8D6F), Color(0xFFFAF3E3), Color(0xFF3B2A21)], category: PaletteCategory.earth),
  AppPalette(id: 'royal_court', name: 'Royal Court', colors: [Color(0xFF6A2C91), Color(0xFFD7A33E), Color(0xFFF4EFE2), Color(0xFF3A1A4A), Color(0xFF1B1620)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'tidewater', name: 'Tidewater', colors: [Color(0xFF0E5C5C), Color(0xFF8FD9C4), Color(0xFFE8DCC0), Color(0xFFE8704F), Color(0xFF102A3B)], category: PaletteCategory.cool),
  AppPalette(id: 'ashfall', name: 'Ashfall', colors: [Color(0xFF8A8784), Color(0xFFD9612B), Color(0xFFEDE6DA), Color(0xFF211E1C), Color(0xFF7A3B23)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'lush_canopy', name: 'Lush Canopy', colors: [Color(0xFF1F4D2C), Color(0xFF7C9070), Color(0xFFA9C49A), Color(0xFF3E2F25), Color(0xFFF1EEDE)], category: PaletteCategory.earth),
  AppPalette(id: 'marigold_dusk', name: 'Marigold Dusk', colors: [Color(0xFFE8A33D), Color(0xFF5B3A5C), Color(0xFFF7EBD8), Color(0xFF2A2420), Color(0xFFB5532E)], category: PaletteCategory.warm),
  AppPalette(id: 'frostline', name: 'Frostline', colors: [Color(0xFFC9E4F2), Color(0xFF4F6B7A), Color(0xFFF7FAFB), Color(0xFF2C3A42), Color(0xFF6FA8B5)], category: PaletteCategory.cool),
  AppPalette(id: 'solar_flare', name: 'Solar Flare', colors: [Color(0xFFFFAA00), Color(0xFFE8003A)], category: PaletteCategory.warm),
  AppPalette(id: 'neon_tide', name: 'Neon Tide', colors: [Color(0xFF00F5AA), Color(0xFF3B00FF)], category: PaletteCategory.cool),
  AppPalette(id: 'arctic', name: 'Arctic', colors: [Color(0xFFE8F5FF), Color(0xFF0050D8)], category: PaletteCategory.cool),
  AppPalette(id: 'dusk', name: 'Dusk', colors: [Color(0xFFFF5CBA), Color(0xFF2B00FF)], category: PaletteCategory.cool),
  AppPalette(id: 'berry_glow', name: 'Berry Glow', colors: [Color(0xFF9333EA), Color(0xFFFB7185)], category: PaletteCategory.vibrant),
  AppPalette(id: 'cotton_candy', name: 'Cotton Candy', colors: [Color(0xFF7AA8FF), Color(0xFFFF9AEF)], category: PaletteCategory.pastel),
  AppPalette(id: 'golden_ember', name: 'Golden Ember', colors: [Color(0xFFFACC15), Color(0xFFF97316)], category: PaletteCategory.warm),
  AppPalette(id: 'aqua_depth', name: 'Aqua Depth', colors: [Color(0xFF0F766E), Color(0xFF22D3EE)], category: PaletteCategory.cool),
  AppPalette(id: 'royal_flame', name: 'Royal Flame', colors: [Color(0xFFDB2777), Color(0xFFDC2626)], category: PaletteCategory.warm),
  AppPalette(id: 'dark_scarlet', name: 'Dark Scarlet', colors: [Color(0xFF4F0715), Color(0xFF781728)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'japanese_carmine', name: 'Japanese Carmine', colors: [Color(0xFF982930), Color(0xFF39544B)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'slate_blue_glacier', name: 'Slate Blue/Glacier', colors: [Color(0xFF619BB6), Color(0xFFBAD7E1)], category: PaletteCategory.cool),
  AppPalette(id: 'thistle_liberty', name: 'Thistle/Liberty', colors: [Color(0xFFDEC2DB), Color(0xFF5B62B3)], category: PaletteCategory.cool),
  AppPalette(id: 'stormy_teal', name: 'Stormy Teal/Iron/Oak', colors: [Color(0xFF32707C), Color(0xFFA8371C), Color(0xFFD4C4B7)], category: PaletteCategory.earth),
  AppPalette(id: 'luxury_soft_oat', name: 'Luxury Noir/Soft Oat', colors: [Color(0xFF060D0C), Color(0xFFF0EDE5)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'liver_tan', name: 'Liver/Tan', colors: [Color(0xFF6A3428), Color(0xFFCFB882)], category: PaletteCategory.earth),
  AppPalette(id: 'bistre_brown_sugar', name: 'Bistre/Brown Sugar', colors: [Color(0xFF3D2C22), Color(0xFFBB734B)], category: PaletteCategory.earth),
  AppPalette(id: 'dark_gray_yellow', name: 'Dark Gray/Yellow', colors: [Color(0xFF323232), Color(0xFFFFDB00)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'jasmine_graphite', name: 'Jasmine/Dark Graphite', colors: [Color(0xFFF8DE7F), Color(0xFF3A393F)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'deep_blue_orange', name: 'Deep Blue/Orange', colors: [Color(0xFF001F7B), Color(0xFFFFBA09)], category: PaletteCategory.cool),
  AppPalette(id: 'dark_neon_green', name: 'Dark Green/Neon Green', colors: [Color(0xFF01210A), Color(0xFFA8FF00)], category: PaletteCategory.vibrant),
  AppPalette(id: 'dark_rich_green_yellow', name: 'Dark Rich Green/Yellow', colors: [Color(0xFF014726), Color(0xFFFFCF00)], category: PaletteCategory.earth),
  AppPalette(id: 'deep_rich_red_yellow', name: 'Deep Rich Red/Soft Yellow', colors: [Color(0xFFAB1509), Color(0xFFFFF8D2)], category: PaletteCategory.warm),
  AppPalette(id: 'dark_red_warm_yellow', name: 'Dark Red/Bright Warm Yellow', colors: [Color(0xFFA01717), Color(0xFFFFE162)], category: PaletteCategory.warm),
  AppPalette(id: 'matcha_cream', name: 'Matcha Cream/Honey', colors: [Color(0xFF9CA763), Color(0xFFF1E8C7)], category: PaletteCategory.earth),
  AppPalette(id: 'coffee_bean_almond', name: 'Coffee Bean/Almond', colors: [Color(0xFF2E0D14), Color(0xFFEFE1D5)], category: PaletteCategory.earth),
  AppPalette(id: 'mocha_berry', name: 'Mocha Berry/Vanilla', colors: [Color(0xFF784955), Color(0xFFFAEDDB)], category: PaletteCategory.earth),
  AppPalette(id: 'twilight', name: 'Twilight', colors: [Color(0xFF564A96), Color(0xFFB75F67)], category: PaletteCategory.cool),
  AppPalette(id: 'blacklist_purple', name: 'Blacklist Purple', colors: [Color(0xFF240A30), Color(0xFFFFDCF0)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'magenta', name: 'Magenta', colors: [Color(0xFF4B0C37), Color(0xFFC8005A)], category: PaletteCategory.vibrant),
  AppPalette(id: 'muted_blue_green', name: 'Muted Blue Green', colors: [Color(0xFF162531), Color(0xFF9AF376)], category: PaletteCategory.cool),
  AppPalette(id: 'deep_rich_purple', name: 'Deep Rich Purple', colors: [Color(0xFF720065), Color(0xFFFDF9B6)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'deep_royal_purple', name: 'Deep Royal Purple', colors: [Color(0xFF460B6A), Color(0xFFFFFBFF)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'deep_navy_cyan', name: 'Deep Navy/Cyan', colors: [Color(0xFF001935), Color(0xFF2FE8FF)], category: PaletteCategory.cool),
  AppPalette(id: 'vanilla_latte', name: 'Vanilla Latte/Teal Forest', colors: [Color(0xFF184E50)], category: PaletteCategory.cool),
  AppPalette(id: 'sage_black_olive', name: 'Sage/Black Olive', colors: [Color(0xFFB2B49C)], category: PaletteCategory.earth),
  AppPalette(id: 'old_rose_seashell', name: 'Old Rose/Seashell/Sky', colors: [Color(0xFFE19AA6), Color(0xFFFAF0EA), Color(0xFF82B0CE)], category: PaletteCategory.pastel),
  AppPalette(id: 'soft_fawn_carbon', name: 'Soft Fawn/Carbon/Ivory', colors: [Color(0xFFD5B572), Color(0xFF201F14), Color(0xFFF8F2E1)], category: PaletteCategory.earth),
  AppPalette(id: 'onyx_olive_desert', name: 'Onyx/Olive/Desert', colors: [Color(0xFF13140E), Color(0xFF838236), Color(0xFFDEDACF)], category: PaletteCategory.earth),
  AppPalette(id: 'fiery_rose_pearl', name: 'Fiery Rose/Black Pearl', colors: [Color(0xFFFF4D73), Color(0xFF00181B)], category: PaletteCategory.vibrant),
  AppPalette(id: 'tranquil_orange', name: 'Tranquil Orange', colors: [Color(0xFFFFB268), Color(0xFF001E37)], category: PaletteCategory.warm),
  AppPalette(id: 'sangria', name: 'Sangria', colors: [Color(0xFFC0392B), Color(0xFF080205)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'forest_night', name: 'Forest Night', colors: [Color(0xFF0A1200), Color(0xFFBD5E85)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'burgundy_mono', name: 'Burgundy', colors: [Color(0xFF4A1528)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'navy_mono', name: 'Navy', colors: [Color(0xFF292F91)], category: PaletteCategory.cool),
  AppPalette(id: 'cyan_spark', name: 'Cyan Spark', colors: [Color(0xFF00D4FF)], category: PaletteCategory.cool),
  AppPalette(id: 'near_black', name: 'Near Black', colors: [Color(0xFF1A0508)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'copper_blaze', name: 'Copper Blaze', colors: [Color(0xFFB5651D), Color(0xFF3A1A0A)], category: PaletteCategory.warm),
  AppPalette(id: 'polar_night', name: 'Polar Night', colors: [Color(0xFF1B2735), Color(0xFF090A0F)], category: PaletteCategory.cool),
  AppPalette(id: 'mango_tango', name: 'Mango Tango', colors: [Color(0xFFFFB347), Color(0xFFFF6F3C)], category: PaletteCategory.warm),
  AppPalette(id: 'velvet_plum', name: 'Velvet Plum', colors: [Color(0xFF5A2A5C), Color(0xFF1A0E1C)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'seaglass_drift', name: 'Seaglass Drift', colors: [Color(0xFF6FBFA0), Color(0xFF1C3D3A)], category: PaletteCategory.cool),
  AppPalette(id: 'crimson_veil', name: 'Crimson Veil', colors: [Color(0xFF8B1E3F), Color(0xFF2B0A12)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'honeycomb', name: 'Honeycomb', colors: [Color(0xFFF4B400), Color(0xFF7A4E00)], category: PaletteCategory.warm),
  AppPalette(id: 'inkwell', name: 'Inkwell', colors: [Color(0xFF2E2B5F), Color(0xFF0B0A1A)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'rosewater_fog', name: 'Rosewater Fog', colors: [Color(0xFFE8B4BC), Color(0xFF5C3A40)], category: PaletteCategory.pastel),
  AppPalette(id: 'verdant_spark', name: 'Verdant Spark', colors: [Color(0xFF2E8B57), Color(0xFF0D2914)], category: PaletteCategory.earth),
  AppPalette(id: 'amber_trail', name: 'Amber Trail', colors: [Color(0xFFC8851A), Color(0xFF4A2E0A)], category: PaletteCategory.warm),
  AppPalette(id: 'glacier_pulse', name: 'Glacier Pulse', colors: [Color(0xFF7FB3D5), Color(0xFF1A3A4A)], category: PaletteCategory.cool),
  AppPalette(id: 'wildfire', name: 'Wildfire', colors: [Color(0xFFFF4E00), Color(0xFF8E0000)], category: PaletteCategory.warm),
  AppPalette(id: 'lagoon_drift', name: 'Lagoon Drift', colors: [Color(0xFF00A8A8), Color(0xFF003C3C)], category: PaletteCategory.cool),
  AppPalette(id: 'plumeria', name: 'Plumeria', colors: [Color(0xFFFFD6E8), Color(0xFF7A2E5C)], category: PaletteCategory.pastel),
  AppPalette(id: 'stormfront', name: 'Stormfront', colors: [Color(0xFF4A5A6A), Color(0xFF0E141A)], category: PaletteCategory.cool),
  AppPalette(id: 'sunburst_clay', name: 'Sunburst Clay', colors: [Color(0xFFE89A3C), Color(0xFF6B3A1E)], category: PaletteCategory.warm),
  AppPalette(id: 'midnight_garnet', name: 'Midnight Garnet', colors: [Color(0xFF6B0F1A), Color(0xFF19060C)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'frosted_lilac', name: 'Frosted Lilac', colors: [Color(0xFFC9B6E4), Color(0xFF3A2C5C)], category: PaletteCategory.pastel),
  AppPalette(id: 'brass_ink', name: 'Brass & Ink', colors: [Color(0xFFB08D57), Color(0xFF1A1A2E)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'boipelo_pick', name: "Boipelo's Pick", colors: [Color(0xFF1565FF)], category: PaletteCategory.special),
  AppPalette(id: 'last_dance', name: 'Last Dance', colors: [Color(0xFFD4AF38), Color(0xFF000000)], category: PaletteCategory.special),
  AppPalette(id: 'apex_legend', name: 'Apex Legend', colors: [Color(0xFF8E0001), Color(0xFF000001)], category: PaletteCategory.special),
  AppPalette(id: 'minecraft_green', name: 'Minecraft Green', colors: [Color(0xFF3D9E3D), Color(0xFF5C4033)], category: PaletteCategory.special),
  AppPalette(id: 'knights_gambit', name: "Knight's Gambit", colors: [Color(0xFFF5F5DC), Color(0xFF722F37)], category: PaletteCategory.special),
  AppPalette(id: 'checkmate', name: 'Checkmate', colors: [Color(0xFF000002), Color(0xFF990000)], category: PaletteCategory.special),
  AppPalette(id: 'endgame', name: 'Endgame', colors: [Color(0xFF708090), Color(0xFFD4AF39)], category: PaletteCategory.special),
  AppPalette(id: 'castling', name: 'Castling', colors: [Color(0xFF000080), Color(0xFFFFFDD0)], category: PaletteCategory.special),
  AppPalette(id: 'bullet_express', name: 'Bullet Express', colors: [Color(0xFF001936), Color(0xFFFFFFFF), Color(0xFFFF8A1F)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'maglev_midnight', name: 'Maglev Midnight', colors: [Color(0xFF0A0A0A), Color(0xFF333333)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'steel_rail', name: 'Steel Rail', colors: [Color(0xFF4682B4), Color(0xFFB0C4DE)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'platform_dusk', name: 'Platform Dusk', colors: [Color(0xFF2F4F4F), Color(0xFFA9A9A9)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'signal_red', name: 'Signal Red', colors: [Color(0xFFFF0000), Color(0xFF000003)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'departure_board', name: 'Departure Board', colors: [Color(0xFF000004), Color(0xFFFFFF00)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'overnight_sleeper', name: 'Overnight Sleeper', colors: [Color(0xFF191970), Color(0xFFD3D3D3)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'coastal_line', name: 'Coastal Line', colors: [Color(0xFF20B2AA), Color(0xFFF0E68C)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'tunnel_vision', name: 'Tunnel Vision', colors: [Color(0xFF000005), Color(0xFF555555)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'last_stop', name: 'Last Stop', colors: [Color(0xFF800000), Color(0xFFFFD700)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'express_lane', name: 'Express Lane', colors: [Color(0xFF0000CD), Color(0xFF000006)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'commuter_gray', name: 'Commuter Gray', colors: [Color(0xFF808080), Color(0xFFDCDCDC)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'diesel_run', name: 'Diesel Run', colors: [Color(0xFFB22222), Color(0xFFF4A460)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'boarding_call', name: 'Boarding Call', colors: [Color(0xFF006400), Color(0xFFE9967A)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'track_switch', name: 'Track Switch', colors: [Color(0xFF4B0082), Color(0xFFDA70D6)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'conductors_brass', name: "Conductor's Brass", colors: [Color(0xFFB8860B), Color(0xFFF5F5F5)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'rail_yard', name: 'Rail Yard', colors: [Color(0xFF708091), Color(0xFFDEB887)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'crossing_light', name: 'Crossing Light', colors: [Color(0xFFFF4500), Color(0xFF000007)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'terminus', name: 'Terminus', colors: [Color(0xFF2F4F50), Color(0xFFFFEFD5)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'high_speed_run', name: 'High-Speed Run', colors: [Color(0xFF00BFFF), Color(0xFFF0F8FF)], category: PaletteCategory.trainTransit),
  AppPalette(id: 'rose_gold', name: 'Rose Gold', colors: [Color(0xFFFB4205), Color(0xFFACFB42)], category: PaletteCategory.warm),
  AppPalette(id: 'sunset_boulevard', name: 'Sunset Boulevard', colors: [Color(0xFFED4495), Color(0xFF24ED44)], category: PaletteCategory.warm),
  AppPalette(id: 'champagne_blush', name: 'Champagne Blush', colors: [Color(0xFF4AD1EA), Color(0xFFCF4AD1)], category: PaletteCategory.warm),
  AppPalette(id: 'amber_glow', name: 'Amber Glow', colors: [Color(0xFF15FD4E), Color(0xFF1C15FD)], category: PaletteCategory.warm),
  AppPalette(id: 'coral_reef', name: 'Coral Reef', colors: [Color(0xFF8CDCDA), Color(0xFFF88CDC)], category: PaletteCategory.warm),
  AppPalette(id: 'honey_bee', name: 'Honey Bee', colors: [Color(0xFFA31DDA), Color(0xFF2BA31D)], category: PaletteCategory.warm),
  AppPalette(id: 'peach_fizz', name: 'Peach Fizz', colors: [Color(0xFFEDA29E), Color(0xFFFDEDA2)], category: PaletteCategory.warm),
  AppPalette(id: 'terracotta', name: 'Terracotta', colors: [Color(0xFFBFD48C), Color(0xFF3BBFD4)], category: PaletteCategory.warm),
  AppPalette(id: 'cherry_blossom', name: 'Cherry Blossom', colors: [Color(0xFF99F63E), Color(0xFFED99F6)], category: PaletteCategory.warm),
  AppPalette(id: 'wine_and_roses', name: 'Wine & Roses', colors: [Color(0xFF00454F), Color(0xFF370045)], category: PaletteCategory.warm),
  AppPalette(id: 'cinnamon_toast', name: 'Cinnamon Toast', colors: [Color(0xFF3F1E46), Color(0xFF443F1E)], category: PaletteCategory.warm),
  AppPalette(id: 'apricot_sun', name: 'Apricot Sun', colors: [Color(0xFFCFF42F), Color(0xFF84CFF4)], category: PaletteCategory.warm),
  AppPalette(id: 'brick_oven', name: 'Brick Oven', colors: [Color(0xFFBBF3DB), Color(0xFFFABBF3)], category: PaletteCategory.warm),
  AppPalette(id: 'maple_syrup', name: 'Maple Syrup', colors: [Color(0xFFE5ECC3), Color(0xFF8AE5EC)], category: PaletteCategory.warm),
  AppPalette(id: 'flamingo', name: 'Flamingo', colors: [Color(0xFFCC0C97), Color(0xFF69CC0C)], category: PaletteCategory.warm),
  AppPalette(id: 'paprika', name: 'Paprika', colors: [Color(0xFF707318), Color(0xFF1D7073)], category: PaletteCategory.warm),
  AppPalette(id: 'golden_hour', name: 'Golden Hour', colors: [Color(0xFFD4A51F), Color(0xFF49D4A5)], category: PaletteCategory.warm),
  AppPalette(id: 'burnt_sienna', name: 'Burnt Sienna', colors: [Color(0xFF1E2277), Color(0xFF4F1E22)], category: PaletteCategory.warm),
  AppPalette(id: 'marigold_field', name: 'Marigold Field', colors: [Color(0xFF990154), Color(0xFFDA9901)], category: PaletteCategory.warm),
  AppPalette(id: 'ember_glow', name: 'Ember Glow', colors: [Color(0xFFAC4063), Color(0xFF93AC40)], category: PaletteCategory.warm),
  AppPalette(id: 'arctic_frost', name: 'Arctic Frost', colors: [Color(0xFFFC5AA1), Color(0xFFADFC5A)], category: PaletteCategory.cool),
  AppPalette(id: 'glacier_blue', name: 'Glacier Blue', colors: [Color(0xFFCE3D84), Color(0xFF65CE3D)], category: PaletteCategory.cool),
  AppPalette(id: 'midnight_ocean', name: 'Midnight Ocean', colors: [Color(0xFFE2D94A), Color(0xFF19E2D9)], category: PaletteCategory.cool),
  AppPalette(id: 'slate_storm', name: 'Slate Storm', colors: [Color(0xFFFE232C), Color(0xFF83FE23)], category: PaletteCategory.cool),
  AppPalette(id: 'mint_frost', name: 'Mint Frost', colors: [Color(0xFFF728C1), Color(0xFFB7F728)], category: PaletteCategory.cool),
  AppPalette(id: 'lavender_mist', name: 'Lavender Mist', colors: [Color(0xFFB33115), Color(0xFFC0B331)], category: PaletteCategory.cool),
  AppPalette(id: 'steel_blue', name: 'Steel Blue', colors: [Color(0xFF633342), Color(0xFF076333)], category: PaletteCategory.cool),
  AppPalette(id: 'periwinkle', name: 'Periwinkle', colors: [Color(0xFFD413FE), Color(0xFF42D413)], category: PaletteCategory.cool),
  AppPalette(id: 'northern_lights', name: 'Northern Lights', colors: [Color(0xFFD0E937), Color(0xFFC7D0E9)], category: PaletteCategory.cool),
  AppPalette(id: 'deep_sea', name: 'Deep Sea', colors: [Color(0xFF586EDA), Color(0xFF8F586E)], category: PaletteCategory.cool),
  AppPalette(id: 'polar_cap', name: 'Polar Cap', colors: [Color(0xFFCFACA8), Color(0xFF35CFAC)], category: PaletteCategory.cool),
  AppPalette(id: 'cobalt_deep', name: 'Cobalt Deep', colors: [Color(0xFF4A5E6F), Color(0xFF5A4A5E)], category: PaletteCategory.cool),
  AppPalette(id: 'winter_pine', name: 'Winter Pine', colors: [Color(0xFFD8DA38), Color(0xFF05D8DA)], category: PaletteCategory.cool),
  AppPalette(id: 'iceberg', name: 'Iceberg', colors: [Color(0xFF3D6080), Color(0xFF6B3D60)], category: PaletteCategory.cool),
  AppPalette(id: 'frosted_glass', name: 'Frosted Glass', colors: [Color(0xFF1A5692), Color(0xFF8C1A56)], category: PaletteCategory.cool),
  AppPalette(id: 'moonlit_bay', name: 'Moonlit Bay', colors: [Color(0xFF444814), Color(0xFFB94448)], category: PaletteCategory.cool),
  AppPalette(id: 'stormwatch', name: 'Stormwatch', colors: [Color(0xFFA87C28), Color(0xFFCDA87C)], category: PaletteCategory.cool),
  AppPalette(id: 'denim_drift', name: 'Denim Drift', colors: [Color(0xFFB59C14), Color(0xFFD8B59C)], category: PaletteCategory.cool),
  AppPalette(id: 'glacial_teal', name: 'Glacial Teal', colors: [Color(0xFF020568), Color(0xFF550205)], category: PaletteCategory.cool),
  AppPalette(id: 'cold_steel', name: 'Cold Steel', colors: [Color(0xFF0D8ED8), Color(0xFF5D0D8E)], category: PaletteCategory.cool),
  AppPalette(id: 'obsidian', name: 'Obsidian', colors: [Color(0xFF5531A9), Color(0xFF305531)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'charcoal_noir', name: 'Charcoal Noir', colors: [Color(0xFF125291), Color(0xFFD81252)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'blackout', name: 'Blackout', colors: [Color(0xFF262084), Color(0xFFF52620)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'graphite', name: 'Graphite', colors: [Color(0xFF0CB136), Color(0xFF880CB1)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'shadow_walker', name: 'Shadow Walker', colors: [Color(0xFF297DFE), Color(0xFFEE297D)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'onyx_edge', name: 'Onyx Edge', colors: [Color(0xFF6C6528), Color(0xFF6E6C65)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'eclipse', name: 'Eclipse', colors: [Color(0xFF4EDD3D), Color(0xFFA24EDD)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'storm_cloud', name: 'Storm Cloud', colors: [Color(0xFFCF4470), Color(0xFFC8CF44)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'iron_gate', name: 'Iron Gate', colors: [Color(0xFF85F11F), Color(0xFF6485F1)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'void', name: 'Void', colors: [Color(0xFF0A752A), Color(0xFFA20A75)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'pitch', name: 'Pitch', colors: [Color(0xFF8FD31A), Color(0xFF8F8FD3)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'carbon_fiber', name: 'Carbon Fiber', colors: [Color(0xFFEFDCBA), Color(0xFF62EFDC)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'midnight_vault', name: 'Midnight Vault', colors: [Color(0xFF2CFD96), Color(0xFF9D2CFD)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'raven', name: 'Raven', colors: [Color(0xFF2D8C51), Color(0xFFCA2D8C)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'tar_pit', name: 'Tar Pit', colors: [Color(0xFF05AF3A), Color(0xFFC405AF)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'nightfall', name: 'Nightfall', colors: [Color(0xFFF3BE9F), Color(0xFF54F3BE)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'abyss', name: 'Abyss', colors: [Color(0xFFED7EF6), Color(0xFFDDED7E)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'smoke_screen', name: 'Smoke Screen', colors: [Color(0xFFF7817E), Color(0xFFBAF781)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'coal_bed', name: 'Coal Bed', colors: [Color(0xFFBA3A85), Color(0xFF76BA3A)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'dark_matter', name: 'Dark Matter', colors: [Color(0xFF006119), Color(0xFFF00061)], category: PaletteCategory.darkMoody),
  AppPalette(id: 'desert_sand', name: 'Desert Sand', colors: [Color(0xFFF60E3B), Color(0xFF1DF60E)], category: PaletteCategory.earth),
  AppPalette(id: 'olive_grove', name: 'Olive Grove', colors: [Color(0xFFBC3CA3), Color(0xFF6EBC3C)], category: PaletteCategory.earth),
  AppPalette(id: 'forest_floor', name: 'Forest Floor', colors: [Color(0xFF1CC2DD), Color(0xFF291CC2)], category: PaletteCategory.earth),
  AppPalette(id: 'cedar_wood', name: 'Cedar Wood', colors: [Color(0xFF4B19CA), Color(0xFF404B19)], category: PaletteCategory.earth),
  AppPalette(id: 'clay_pot', name: 'Clay Pot', colors: [Color(0xFF3A790C), Color(0xFF223A79)], category: PaletteCategory.earth),
  AppPalette(id: 'autumn_leaf', name: 'Autumn Leaf', colors: [Color(0xFF30CCB1), Color(0xFFE030CC)], category: PaletteCategory.earth),
  AppPalette(id: 'mossy_stone', name: 'Mossy Stone', colors: [Color(0xFF847260), Color(0xFF448472)], category: PaletteCategory.earth),
  AppPalette(id: 'terra_firma', name: 'Terra Firma', colors: [Color(0xFFF50687), Color(0xFF34F506)], category: PaletteCategory.earth),
  AppPalette(id: 'walnut', name: 'Walnut', colors: [Color(0xFFBA464B), Color(0xFF38BA46)], category: PaletteCategory.earth),
  AppPalette(id: 'harvest_gold', name: 'Harvest Gold', colors: [Color(0xFFF23E37), Color(0xFF0FF23E)], category: PaletteCategory.earth),
  AppPalette(id: 'canyon_ridge', name: 'Canyon Ridge', colors: [Color(0xFFA3FDBC), Color(0xFFE8A3FD)], category: PaletteCategory.earth),
  AppPalette(id: 'driftclay', name: 'Driftclay', colors: [Color(0xFF77211F), Color(0xFFD77721)], category: PaletteCategory.earth),
  AppPalette(id: 'redwood', name: 'Redwood', colors: [Color(0xFFF72B99), Color(0xFF21F72B)], category: PaletteCategory.earth),
  AppPalette(id: 'prairie_dust', name: 'Prairie Dust', colors: [Color(0xFF61B62A), Color(0xFF4261B6)], category: PaletteCategory.earth),
  AppPalette(id: 'loam', name: 'Loam', colors: [Color(0xFF778461), Color(0xFFA47784)], category: PaletteCategory.earth),
  AppPalette(id: 'stonewash', name: 'Stonewash', colors: [Color(0xFF1A2119), Color(0xFF4B1A21)], category: PaletteCategory.earth),
  AppPalette(id: 'bark_and_moss', name: 'Bark & Moss', colors: [Color(0xFF8060A9), Color(0xFF2D8060)], category: PaletteCategory.earth),
  AppPalette(id: 'sienna_trail', name: 'Sienna Trail', colors: [Color(0xFF642C1F), Color(0xFF4F642C)], category: PaletteCategory.earth),
  AppPalette(id: 'highland_peat', name: 'Highland Peat', colors: [Color(0xFFC4156A), Color(0xFF6BC415)], category: PaletteCategory.earth),
  AppPalette(id: 'sandstone', name: 'Sandstone', colors: [Color(0xFF6DB37B), Color(0xFFFB6DB3)], category: PaletteCategory.earth),
  AppPalette(id: 'electric_lime', name: 'Electric Lime', colors: [Color(0xFF14C0DD), Color(0xFFD914C0)], category: PaletteCategory.vibrant),
  AppPalette(id: 'neon_pink', name: 'Neon Pink', colors: [Color(0xFFCA4F0C), Color(0xFF9CCA4F)], category: PaletteCategory.vibrant),
  AppPalette(id: 'cyber_purple', name: 'Cyber Purple', colors: [Color(0xFF62B247), Color(0xFF5262B2)], category: PaletteCategory.vibrant),
  AppPalette(id: 'tropic_punch', name: 'Tropic Punch', colors: [Color(0xFF031321), Color(0xFF880313)], category: PaletteCategory.vibrant),
  AppPalette(id: 'bubblegum', name: 'Bubblegum', colors: [Color(0xFF3CC1EE), Color(0xFF7D3CC1)], category: PaletteCategory.vibrant),
  AppPalette(id: 'laser_blue', name: 'Laser Blue', colors: [Color(0xFF083387), Color(0xFF5C0833)], category: PaletteCategory.vibrant),
  AppPalette(id: 'hot_magenta', name: 'Hot Magenta', colors: [Color(0xFFD2056C), Color(0xFF53D205)], category: PaletteCategory.vibrant),
  AppPalette(id: 'acid_wash', name: 'Acid Wash', colors: [Color(0xFF84C60D), Color(0xFF2584C6)], category: PaletteCategory.vibrant),
  AppPalette(id: 'retro_arcade', name: 'Retro Arcade', colors: [Color(0xFF5DD68A), Color(0xFF405DD6)], category: PaletteCategory.vibrant),
  AppPalette(id: 'volt_yellow', name: 'Volt Yellow', colors: [Color(0xFF0F42D6), Color(0xFFC20F42)], category: PaletteCategory.vibrant),
  AppPalette(id: 'plasma_red', name: 'Plasma Red', colors: [Color(0xFFB7C4FD), Color(0xFF05B7C4)], category: PaletteCategory.vibrant),
  AppPalette(id: 'ultraviolet', name: 'Ultraviolet', colors: [Color(0xFFAB28B7), Color(0xFFABAB28)], category: PaletteCategory.vibrant),
  AppPalette(id: 'highlighter_green', name: 'Highlighter Green', colors: [Color(0xFFC0DD33), Color(0xFFA2C0DD)], category: PaletteCategory.vibrant),
  AppPalette(id: 'synthwave_pink', name: 'Synthwave Pink', colors: [Color(0xFF9E77B7), Color(0xFFDC9E77)], category: PaletteCategory.vibrant),
  AppPalette(id: 'radioactive', name: 'Radioactive', colors: [Color(0xFF521299), Color(0xFFCC5212)], category: PaletteCategory.vibrant),
  AppPalette(id: 'power_surge', name: 'Power Surge', colors: [Color(0xFF7D36ED), Color(0xFF107D36)], category: PaletteCategory.vibrant),
  AppPalette(id: 'neon_sign', name: 'Neon Sign', colors: [Color(0xFF6FBBA9), Color(0xFF1C6FBB)], category: PaletteCategory.vibrant),
  AppPalette(id: 'strobe_blue', name: 'Strobe Blue', colors: [Color(0xFFD90771), Color(0xFF52D907)], category: PaletteCategory.vibrant),
  AppPalette(id: 'powder_blue', name: 'Powder Blue', colors: [Color(0xFF7B35D7), Color(0xFFB27B35)], category: PaletteCategory.pastel),
  AppPalette(id: 'buttercream', name: 'Buttercream', colors: [Color(0xFFEB78BF), Color(0xFFE7EB78)], category: PaletteCategory.pastel),
  AppPalette(id: 'sage_whisper', name: 'Sage Whisper', colors: [Color(0xFFB2F680), Color(0xFFEDB2F6)], category: PaletteCategory.pastel),
  AppPalette(id: 'blush_pink', name: 'Blush Pink', colors: [Color(0xFF2B3FEE), Color(0xFFEB2B3F)], category: PaletteCategory.pastel),
  AppPalette(id: 'lilac_dream', name: 'Lilac Dream', colors: [Color(0xFFF1C0B7), Color(0xFFD3F1C0)], category: PaletteCategory.pastel),
  AppPalette(id: 'vanilla_cream', name: 'Vanilla Cream', colors: [Color(0xFF9FF570), Color(0xFFF39FF5)], category: PaletteCategory.pastel),
  AppPalette(id: 'seafoam', name: 'Seafoam', colors: [Color(0xFFDFB6CC), Color(0xFF0FDFB6)], category: PaletteCategory.pastel),
  AppPalette(id: 'dusty_rose', name: 'Dusty Rose', colors: [Color(0xFFE30B4E), Color(0xFFB0E30B)], category: PaletteCategory.pastel),
  AppPalette(id: 'cloud_nine', name: 'Cloud Nine', colors: [Color(0xFFCB60D7), Color(0xFF76CB60)], category: PaletteCategory.pastel),
  AppPalette(id: 'cotton_sky', name: 'Cotton Sky', colors: [Color(0xFF501BAE), Color(0xFFAF501B)], category: PaletteCategory.pastel),
  AppPalette(id: 'mint_macaron', name: 'Mint Macaron', colors: [Color(0xFF0864C5), Color(0xFFAC0864)], category: PaletteCategory.pastel),
  AppPalette(id: 'soft_peach', name: 'Soft Peach', colors: [Color(0xFFB94237), Color(0xFFE6B942)], category: PaletteCategory.pastel),
  AppPalette(id: 'baby_lilac', name: 'Baby Lilac', colors: [Color(0xFFC25200), Color(0xFFF1C252)], category: PaletteCategory.pastel),
  AppPalette(id: 'pale_mimosa', name: 'Pale Mimosa', colors: [Color(0xFFC428CA), Color(0xFFF1C428)], category: PaletteCategory.pastel),
  AppPalette(id: 'whisper_gray', name: 'Whisper Gray', colors: [Color(0xFFC6EF8B), Color(0xFF4BC6EF)], category: PaletteCategory.pastel),
  AppPalette(id: 'petal_pink', name: 'Petal Pink', colors: [Color(0xFF5D620E), Color(0xFF5B5D62)], category: PaletteCategory.pastel),
  AppPalette(id: 'grayscale_pro', name: 'Grayscale Pro', colors: [Color(0xFF0FE901), Color(0xFFEC0FE9)], category: PaletteCategory.monochrome),
  AppPalette(id: 'paper_white', name: 'Paper White', colors: [Color(0xFFE2E514), Color(0xFF49E2E5)], category: PaletteCategory.monochrome),
  AppPalette(id: 'ink_black', name: 'Ink Black', colors: [Color(0xFFDE41D3), Color(0xFFA9DE41)], category: PaletteCategory.monochrome),
  AppPalette(id: 'concrete', name: 'Concrete', colors: [Color(0xFFFC4F3E), Color(0xFF9BFC4F)], category: PaletteCategory.monochrome),
  AppPalette(id: 'fog_bank', name: 'Fog Bank', colors: [Color(0xFF0D8802), Color(0xFFD70D88)], category: PaletteCategory.monochrome),
  AppPalette(id: 'slate_mono', name: 'Slate Mono', colors: [Color(0xFFE2843C), Color(0xFF23E284)], category: PaletteCategory.monochrome),
  AppPalette(id: 'stone_gray', name: 'Stone Gray', colors: [Color(0xFFF5D545), Color(0xFF53F5D5)], category: PaletteCategory.monochrome),
  AppPalette(id: 'newsprint', name: 'Newsprint', colors: [Color(0xFFB83964), Color(0xFF9CB839)], category: PaletteCategory.monochrome),
  AppPalette(id: 'sapphire_court', name: 'Sapphire Court', colors: [Color(0xFFCF395B), Color(0xFFF7CF39)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'emerald_city', name: 'Emerald City', colors: [Color(0xFF3AD6AC), Color(0xFFA23AD6)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'ruby_reign', name: 'Ruby Reign', colors: [Color(0xFFE8B908), Color(0xFFE2E8B9)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'topaz_glow', name: 'Topaz Glow', colors: [Color(0xFFA5EEE9), Color(0xFFACA5EE)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'amethyst_vault', name: 'Amethyst Vault', colors: [Color(0xFF718D0C), Color(0xFFA7718D)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'garnet_deep', name: 'Garnet Deep', colors: [Color(0xFFC8DFC1), Color(0xFF25C8DF)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'citrine_spark', name: 'Citrine Spark', colors: [Color(0xFF0664DC), Color(0xFFAB0664)], category: PaletteCategory.jewelTones),
  AppPalette(id: 'tourmaline', name: 'Tourmaline', colors: [Color(0xFF788140), Color(0xFF017881)], category: PaletteCategory.jewelTones),
];
